### ISSUE TITLE
Visual cues on beat

### ISSUE THREAD

**Issue by jassler** [learning2makethings/HapticTouch#4]
Add visual indicators that signal a beat. This can be color flashing, an object moving from side to side, or anything else.

**Comment by TeddyRugby9** [comment]
This will be the next issue I work on

**Comment by learning2makethings** [comment]
This is possible now using the notifications created in the latest pull request https://github.com/learning2makethings/HapticTouch/pull/22. It will be up to the designer of each Metronome Design to implement it. If a specific kind of visual cue is desired create a new issue with specifics.

**Comment by learning2makethings** [comment]
Reopened until merged into master.
