### ISSUE TITLE
Why does the app ask to use microphone?

### ISSUE THREAD

**Issue by learning2makethings** [learning2makethings/HapticTouch#9]
I don't think that microphone access should be needed.

**Comment by jassler** [comment]
Huh that's strange. It didn't ask for microphone access on my device. I tried deleting and reinstalling the app. Is there another way to "revert" the app to its state when it's first installed?

**Comment by TeddyRugby9** [comment]
I have not seen microphone access requested either

**Comment by learning2makethings** [comment]
Hmm, ill see if i can recreate it.

**Comment by learning2makethings** [comment]
I can't seem to recreate this. If it pops up again I will reopen.
